### PR TITLE
fixed: take into account non standard 'tags' fields

### PR DESCRIPTION
**Pull request by oseg**
Fix issue #7

### CODE REVIEW

**Comment by oseg** [comment]
I have just realized that there is a HACK in tag_tools_rules_get_tag_names() to prevent the call to elgg_get_registered_tag_metadata_names().

I don't see any issue with elgg_get_registered_tag_metadata_names() in elgg v2.3, I don't think this HACK is still needed.

**Comment by oseg** [comment]
I implemented the non standard 'tags' fields in:
- autocomplete suggestion
- create and update metadata notifications
- activity page
- admin search
Hope I didn't forget anything

**Comment by jdalsem** [comment]
I think this feature should go in the Elgg 3.0 version of the plugin. Are you able to redo the PR for the master branch?

**Comment by oseg** [comment]
I am sorry, I am not familiar with elgg 3, still under elgg 2.3.

**Comment by jdalsem** [comment]
If you still need this an new PR for the Elgg 4 version of this plugin needs to be made

**Pull request closed without merging**
